server:
  port: 8080
  servlet:
    context-path: /pricetest

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: akkodis
  jpa:
    spring:
      database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      data-locations=data.sql
  jackson:
    time-zone: UTC